### ISSUE TITLE
ES6 not supported by uglify

### ISSUE THREAD

**Issue by hermith** [kunokdev/react-window-size-listener#1]
I'm using create-react-app which uses uglify for the production build.

Issue as described here: https://github.com/facebookincubator/create-react-app/issues/984

Not sure if this issue is relevant for this library, feel free to close it if you do not think it applies.

**Comment by kunokdev** [comment]
Yes it's related to this package, I will fix this asap and update package

**Comment by kunokdev** [comment]
Hi @hermith I made update. I am now using component generator build for this package and I tested it with Next.js build and it worked, I also successfully built `create-react-app` sample, even tho I  haven't tested deployment part but I think it should work properly now.

**Comment by hermith** [comment]
Seems to work fine now. Thanks for the quick fix.
