### ISSUE TITLE
Support react 16?

### ISSUE THREAD

**Issue by vladimirvolek** [kunokdev/react-window-size-listener#3]
```
react-window-size-listener@1.0.8 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by kunokdev** [comment]
Hi @vladimirvolek I've made this commit: https://github.com/kunokdev/react-window-size-listener/commit/c815e18b8998aa07614352028cbb1ffec15ad11b

which should now make sure that both React versions >15 and 16 are listed as peer dependency.
```
-    "react-dom": "*15.0.0"
+    "react-dom": ">=15.0.0 <= 16"
```
Can you confirm it works ok for you?

**Comment by vladimirvolek** [comment]
Lovely, it's working. Thank you!
