### ISSUE TITLE
Unsafe lifecycle methods: componentWillReceiveProps

### ISSUE THREAD

**Issue by 0xdevalias** [kunokdev/react-window-size-listener#5]
```
index.js:1452 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at src/index.js:21)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: t

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

Ref: https://github.com/kunokdev/react-window-size-listener/blob/c4463ad9375efb78854f62a985777b55aa4ad0fd/src/index.js#L46-L51

**Comment by kunokdev** [comment]
I can update this within few days, if it's blocking you, I will accept PR

**Comment by kunokdev** [comment]
I replaced this method with `componentDidUpdate`. If this behavior is causing issues to anybody, please let me know. This issue is resolved, closing.
