### ISSUE TITLE
HOC returning undefined on initialization

### ISSUE THREAD

**Issue by ygerg** [kunokdev/react-window-size-listener#7]
Wrapping a component receives undefined for size before the first listener event occurs after the debounce time. This results in bouncing divs on initial render, if the window size is used e.g. to define layout direction or size.

Instead, is it worth considering to initialize the HOC state with the current values instead:

```javascript 
this.state = {
        windowSize: {
          windowWidth:
          window.innerWidth ||
          document.documentElement.clientWidth ||
          document.body.clientWidth,
         windowHeight:
          window.innerHeight ||
          document.documentElement.clientHeight ||
          document.body.clientHeight
        }
      };
```

**Comment by kunokdev** [comment]
This change is now [applied](https://github.com/kunokdev/react-window-size-listener/commit/31b8c70b5254eeae285e76220cd4ef68a9f751f5) starting from 1.4.0

**Comment by ygerg** [comment]
Thanks, awesome!

Krunoslav Banovac <notifications@github.com> schrieb am Do., 16. Mai 2019,
23:10:
